export const FETCH_BANNER = "FETCH_BANNER"; 
export const FETCH_BANNER_SUCCESS = "FETCH_BANNER_SUCCESS";
export const FETCH_BANNER_FAILURE = "FETCH_BANNER_FAILURE";


export const FETCH_SHOWCASE = "FETCH_SHOWCASE"; 
export const FETCH_SHOWCASE_SUCCESS = "FETCH_SHOWCASE_SUCCESS";
export const FETCH_SHOWCASE_FAILURE = "FETCH_SHOWCASE_FAILURE";


export const FETCH_TESTIMONIAL = "FETCH_TESTIMONIAL";
export const FETCH_TESTIMONIAL_SUCCESS = "FETCH_TESTIMONIAL_SUCCESS";
export const FETCH_TESTIMONIAL_FAILURE = "FETCH_TESTIMONIAL_FAILURE";


export const FETCH_FAQ = "FETCH_FAQ";
export const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
export const FETCH_FAQ_FAILURE = "FETCH_FAQ_FAILURE";
