export const FETCH_DISCOVER_DATA = "FETCH_DISCOVER_DATA";
export const FETCH_DISCOVER_DATA_SUCCESS = "FETCH_DISCOVER_DATA_SUCCESS";
export const FETCH_DISCOVER_DATA_FAILURE = "FETCH_DISCOVER_DATA_FAILURE";
