export const FETCH_INVEST = "FETCH_INVEST"; 
export const FETCH_INVEST_SUCCESS = "FETCH_INVEST_SUCCESS";
export const FETCH_INVEST_FAILURE = "FETCH_INVEST_FAILURE";


export const FETCH_ISSUERS = "FETCH_ISSUERS"; 
export const FETCH_ISSUERS_SUCCESS = "FETCH_ISSUERS_SUCCESS";
export const FETCH_ISSUERS_FAILURE = "FETCH_ISSUERS_FAILURE";


//this is for the compare and return 
export const FETCH_COMPARE_RETURN = "FETCH_COMPARE_RETURN";
export const FETCH_COMPARE_RETURN_SUCCESS = "FETCH_COMPARE_RETURN_SUCCESS";
export const FETCH_COMPARE_RETURN_FAILURE = "FETCH_COMPARE_RETURN_FAILURE";
