export const FETCH_PORTFOLIO = "FETCH_PORTFOLIO"; 
export const FETCH_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const FETCH_PORTFOLIO_FAILURE = "FETCH_PORTFOLIO_FAILURE";

export const FETCH_PASSBOOK = "FETCH_PASSBOOK"; 
export const FETCH_PASSBOOK_SUCCESS = "FETCH_PASSBOOK_SUCCESS";
export const FETCH_PASSBOOK_FAILURE = "FETCH_PASSBOOK_FAILURE";

//this is for the investment details
export const FETCH_INVESTMENT_DETAILS = "FETCH_INVESTMENT_DETAILS";
export const FETCH_INVESTMENT_DETAILS_SUCCESS = "FETCH_INVESTMENT_DETAILS_SUCCESS";
export const FETCH_INVESTMENT_DETAILS_FAILURE = "FETCH_INVESTMENT_DETAILS_FAILURE";
