// Action types for fetching bank details
export const FETCH_BANK_DETAILS = "FETCH_BANK_DETAILS";
export const FETCH_BANK_DETAILS_SUCCESS = "FETCH_BANK_DETAILS_SUCCESS";
export const FETCH_BANK_DETAILS_FAILURE = "FETCH_BANK_DETAILS_FAILURE";

// Action types for fetching profile details
export const FETCH_PROFILE_DETAILS = "FETCH_PROFILE_DETAILS";
export const FETCH_PROFILE_DETAILS_SUCCESS = "FETCH_PROFILE_DETAILS_SUCCESS";
export const FETCH_PROFILE_DETAILS_FAILURE = "FETCH_PROFILE_DETAILS_FAILURE";

// Action types for fetching main profile details
export const FETCH_MAIN_PROFILE_DETAILS = "FETCH_MAIN_PROFILE_DETAILS";
export const FETCH_MAIN_PROFILE_DETAILS_SUCCESS =
  "FETCH_MAIN_PROFILE_DETAILS_SUCCESS";
export const FETCH_MAIN_PROFILE_DETAILS_FAILURE =
  "FETCH_MAIN_PROFILE_DETAILS_FAILURE";

// Action types for DELETING the user
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
