export const GET_PERSONAL_INFO = "GET_PERSONAL_INFO";
export const GET_PERSONAL_INFO_SUCCESS = "GET_PERSONAL_INFO_SUCCESS";
export const GET_PERSONAL_INFO_FAILURE = "GET_PERSONAL_INFO_FAILURE";


export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const UPDATE_PERSONAL_INFO_SUCCESS = "UPDATE_PERSONAL_INFO_SUCCESS";
export const UPDATE_PERSONAL_INFO_FAILURE = "UPDATE_PERSONAL_INFO_FAILURE";